#3 created user-related entities
JavaIIPlus01/service-reservation-system pull request #12
Opened 2021-05-28 19:58 UTC by MaryR-code

Created user-related entities:
1. UserEntity
2. RoleEntity

2021-05-29 07:33 UTC, dima-fedotovs requested changes
Good code style, formatting. Only thing need to be improved - ids cannot be autogenerated here.
Optionally List of Roles could be changed to Set of Roles.

2021-05-29 07:33 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/RoleEntity.java
> +    private String name;
It isn't defined on diagram (my bad), but role's name should be unique.

2021-05-29 07:33 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/RoleEntity.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
UUID won't be autogenerated. The idea of UUID that we can set it even before inserting to DB

2021-05-29 07:33 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
UUID is not autoincrementable

2021-05-29 07:33 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    )
Good job! :)

2021-05-29 07:33 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    private List<RoleEntity> roles;
Roles are unique per user. There are no cases when user is "admin" twice. So better to migrate it to Set.
It isn't a bug - everything will work correctly even with List. More like "ideological" thing.

2021-05-29 08:47 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/entity/RoleEntity.java
> +    private String name;
added

2021-05-29 08:47 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    )
thanks!

2021-05-29 08:48 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    private List<RoleEntity> roles;
changed

2021-05-29 08:52 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/entity/RoleEntity.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
I hope it's fixed too

2021-05-29 17:50 UTC, yekaterinasavelyeva approved these changes

2021-05-29 18:36 UTC, dima-fedotovs requested changes
insertable = false - was a bad choice. Hibernate will try to insert NULL to the corresponding column, so never will work.

2021-05-29 18:36 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    @Column(name = "id", insertable = false, updatable = false, nullable = false)
the same as above

2021-05-29 18:36 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/RoleEntity.java
> +    @Column(name="id", insertable = false, updatable = false, nullable = false)
Must be insertable. Updatable could be false (I have never tried this, but should be ok)
Nullable = false isn't required, as it is assumed with @Id annotation

2021-05-29 20:59 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/entity/UserEntity.java
> +    @Column(name = "id", insertable = false, updatable = false, nullable = false)
done!

2021-05-29 20:59 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/entity/RoleEntity.java
> +    @Column(name="id", insertable = false, updatable = false, nullable = false)
done!

2021-05-30 10:57 UTC, dima-fedotovs approved these changes
I'm out of comments. Seems this PR can be merged.

2021-05-31 06:02 UTC, merged