Created service-related entities.
JavaIIPlus01/service-reservation-system pull request #13
Opened 2021-05-30 00:13 UTC by andrey-makeyev

Pay attention to mappings. I'm afraid there's a misunderstanding with your vision of how it should be.

2021-05-30 09:48 UTC, yekaterinasavelyeva requested changes

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ReservationEntity.java
> +    private Integer serviceProvider;
According to described mapping this should be ServiceProviderEntity, use @JoinColumn annotation to describe mapping

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ReservationEntity.java
> +    private Integer client;
UserEntity instead of Integer, look to previous comment.

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ReservationEntity.java
> +}
Generate useful toString, equals and hashCode methods.

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceEntity.java
> +
According to specification ServiceEntity does not hold set of ServiceProviderEntity

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceEntity.java
> +}
Useful toString, equals and hashCode methods missing

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceProviderEntity.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
UUID is not auto-generated

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceProviderEntity.java
> +    private Integer service;
Same as previously - there should be UserEntity and ServiceEntity, no Integer. 
It should look like
@ManyToOne(optional = false)
@JoinColumn(name="master_user_id", nullable = false)
private UserEntity master;

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceProviderEntity.java
> +
Remove, as this is not mentioned upon specification

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ReservationEntity.java
> +public class ReservationEntity {
implements Serializable, same in following entity classes.

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceProviderEntity.java
> +}
Useful toString, equals, hashCode methods missing.

2021-05-30 09:48 UTC, yekaterinasavelyeva commented on src/main/java/guru/bug/courses/srs/entity/ServiceEntity.java
> +    private String description;
for name and description fields add constraints eg  @Column(name = "name", length = 50)

2021-05-30 11:07 UTC, dima-fedotovs requested changes
There are some misreads of the specification (diagrams). If you have a better idea regarding how to implement it - let's discuss it in slack first. Diagrams can be changed if we found a better way.

2021-05-30 11:07 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/entity/ReservationEntity.java
> +}
There are examples in previous projects and in this project as well. Look to UserEntity/RoleEntity.
* It is minimum toString which returns class name of the entity and it's id.
* equals/hashCode must work with ID as well. I don't know how much it is good as a common approach, but never had problems doing that.

2021-06-01 20:02 UTC, dima-fedotovs commented
I've created all entities and one DAO. Other daos will be done in other issues

2021-06-01 20:16 UTC, yekaterinasavelyeva approved these changes
Looks perfect

2021-06-01 20:28 UTC, dima-fedotovs approved these changes
seems done

2021-06-01 20:28 UTC, merged