#10 created RoleResource services
JavaIIPlus01/service-reservation-system pull request #20
Opened 2021-06-02 09:59 UTC by MaryR-code

Create RoleResource services

Get list of Roles
Create a new Role

Still no idea how to set access only for admin...

2021-06-02 16:35 UTC, dima-fedotovs requested changes
cleanup is required (see comments)

2021-06-02 16:35 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    //@RolesAllowed({"admin"})
Why is it commented out? Looks correct

2021-06-02 16:35 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/control/RoleControl.java
> +        em.persist(role);
There is a RoleDAO with the same code. It is better to call it.

2021-06-02 16:35 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    //@RolesAllowed({"admin"})
that should be right (if uncomment)

2021-06-02 16:35 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    String userIdClaim;
variable isn't in use - can be deleted

2021-06-02 16:35 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    UserControl userControl;
variable isn't in use - can be deleted

2021-06-02 19:17 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    //@RolesAllowed({"admin"})
I used finaly @PermitAll

2021-06-02 19:17 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/control/RoleControl.java
> +        em.persist(role);
done

2021-06-02 19:18 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    String userIdClaim;
done

2021-06-02 19:18 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    //@RolesAllowed({"admin"})
+

2021-06-02 19:19 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    UserControl userControl;
+

2021-06-07 07:06 UTC, dima-fedotovs requested changes
Some small fixes should be done before merging. See comments.

2021-06-07 07:06 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +        if (sec.isUserInRole("admin")) {
@RolesAllowed is more preferable.

2021-06-07 07:06 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    public List<RoleEntity> getRoles(@Context SecurityContext sec) {
please add @Produces annotation.

2021-06-07 07:06 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +            LOG.info("Creating new role...");
It is ok to log the creation of the role to the INFO level. Would be more useful adding a name of the created role to the log as well.

2021-06-07 07:06 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +            LOG.info("Selecting list of roles...");
I suggest using DEBUG level in this case. I mean nobody wants to know how often and how many times roles were selected in production. But could be useful when debugging.

2021-06-07 07:06 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    public RoleEntity setRole(@Valid @NotNull RoleEntity role,
the name of the method doesn't correspond to real action. Should be "addRole" or "createRole"

2021-06-07 08:40 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    public RoleEntity setRole(@Valid @NotNull RoleEntity role,
changed "createRole"

2021-06-07 08:41 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +        if (sec.isUserInRole("admin")) {
done

2021-06-07 08:41 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +            LOG.info("Creating new role...");
added a name of the created role

2021-06-07 08:41 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +    public List<RoleEntity> getRoles(@Context SecurityContext sec) {
done

2021-06-07 08:41 UTC, MaryR-code commented on src/main/java/guru/bug/courses/srs/boundary/RoleResource.java
> +        if (sec.isUserInRole("admin")) {
changed

2021-06-08 09:53 UTC, dima-fedotovs approved these changes

2021-06-08 09:54 UTC, dima-fedotovs commented
Seems everything is alright. Additional alignment could be done in separate tasks (will add).

2021-06-09 07:24 UTC, merged