#18 insert default roles
JavaIIPlus01/service-reservation-system pull request #24
Opened 2021-06-11 11:17 UTC by MaryR-code

Added default roles:
- client
- master
- admin

2021-06-12 07:07 UTC, dima-fedotovs requested changes
Need to remove the "dbms" attribute, as it could lead to problems in future when (if) project will be switched to another database.

2021-06-12 07:07 UTC, dima-fedotovs commented on src/main/resources/db/changeLog-0001-user.xml
> +        <insert tableName="roles" dbms="h2">
"dbms" is required only in case when a change that is very specific for a particular database. If we decide to switch to Postgres (for example), we still need these roles, and the content of the change doesn't change because of the database.

2021-06-12 07:33 UTC, MaryR-code commented on src/main/resources/db/changeLog-0001-user.xml
> +        <insert tableName="roles" dbms="h2">
Thanks for the comment, done!

2021-06-13 18:20 UTC, dima-fedotovs approved these changes

2021-06-14 10:47 UTC, merged