#22 Improve Exception handling
JavaIIPlus01/service-reservation-system pull request #25
Opened 2021-06-12 15:20 UTC by yekaterinasavelyeva

2021-06-14 18:30 UTC, dima-fedotovs requested changes
Some minor adjustments required :)

2021-06-14 18:30 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/control/PasswordHashEngine.java
> +            throw new ServiceException("Service error occurred");
Exceptions should be chained to not to lose the information about the original exception.
(the cause-parameter in Exception's constructor)

2021-06-14 18:30 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/control/PasswordHashEngine.java
> +            LOG.error("Couldn't hash password", e);
Sonar is saying, that you can do either logging of the exception or either rethrowing. Not both.
This is because of huge unreadable logs when an exception is logged and rethrown, then logged on another level and rethrow again... 
https://rules.sonarsource.com/java/RSPEC-2139

2021-06-18 21:00 UTC, dima-fedotovs approved these changes
One thing could be improved - Probably service exception should be finally converted to 500, not 400 because it can be possible only if something is wrong on the server.
All 4xx errors are about errors related to the request.

2021-06-19 09:17 UTC, MaryR-code approved these changes
Looks good!

2021-06-26 06:57 UTC, merged