#11 create ServiceResourse services
JavaIIPlus01/service-reservation-system pull request #26
Opened 2021-06-14 18:15 UTC by MaryR-code

- Get list of services
- Get a single service by Id
- Create a new service (POST)
- Update a service (PUT)

There are no tests for new methods in ServiceDAO and for classes ServiceControl, ServiceResourse.
Will be added!

2021-06-14 18:41 UTC, dima-fedotovs requested changes
Would be nice to add more tests

2021-06-14 18:41 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/ServiceResource.java
> +        LOG.info("Searching for service by id {}", id);
info is too much. Should be logged to debug

2021-06-14 18:41 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/ServiceResource.java
> +        LOG.info("Creating new service with name '{}'", service.getName());
probably better to log to debug. But this is not a frequent operation, so may be useful as info too.

2021-06-14 18:41 UTC, dima-fedotovs commented on src/main/java/guru/bug/courses/srs/boundary/ServiceResource.java
> +        LOG.info("Updating service id {} -> name {}; description {}; duration {}",
probably better to log to debug. But this is not a frequent operation, so may be useful as info too.

2021-06-19 22:31 UTC, MaryR-code commented on src/test/java/guru/bug/courses/srs/boundary/ServiceResourceTest.java
> +                //.body("name", is(service.getName()));
I would like to add a test with statusCode(200), but it works only for @PermitAll in ServiceResource POST-method... 
How can I do it for "admin" role?

2021-06-26 17:39 UTC, yekaterinasavelyeva commented on src/test/java/guru/bug/courses/srs/boundary/ServiceResourceTest.java
> +                //.body("name", is(service.getName()));
This will do the trick:
adding in pom.xml dependency
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-security</artifactId>
            <scope>test</scope>
            <version>2.0.0.Final</version>
        </dependency>

And then the test will look like

  @Test
    @TestSecurity(user = "testUser", roles = {"admin", "user"})
    void createServiceOk() {
        ServiceEntity service = new ServiceEntity();
        service.setName("create-new-service-ok");
        service.setDescription("new-service-ok");
        service.setDefaultDuration(20);

        given()
                .contentType(MediaType.APPLICATION_JSON)
                .body(service)
                .when().post("/services")
                .then()
                .statusCode(200)
        .body("name", is(service.getName()));
    }

2021-06-27 21:17 UTC, MaryR-code commented on src/test/java/guru/bug/courses/srs/boundary/ServiceResourceTest.java
> +                //.body("name", is(service.getName()));
@yekaterinasavelyeva thank you! It works!

2021-07-02 16:32 UTC, dima-fedotovs requested changes
A couple of small changes required.

2021-07-02 16:32 UTC, dima-fedotovs commented on pom.xml
> +            <version>2.0.0.Final</version>
You don't need to specify the version (and 2.0.0 isn't the right version to use). 
There is the import of quarkus BOM, so all compatible versions are listed there. You need to specify dependency. The version will be based on imported BOM.

2021-07-02 16:32 UTC, dima-fedotovs commented on src/test/java/guru/bug/courses/srs/boundary/ServiceResourceTest.java
> +        System.out.println(resp);
it isn't good practice to print responses. You need to validate responses using the assertions

2021-07-02 16:47 UTC, dima-fedotovs requested changes
There is a failing test because of an earlier bug in changeLog-0002.xml 
There is a unique constraint on the default_duration_minutes column. This is a mistake. The column default_duration_minutes cannot be unique.

2021-07-04 08:17 UTC, MaryR-code commented on pom.xml
> +            <version>2.0.0.Final</version>
done

2021-07-04 08:25 UTC, MaryR-code commented on src/test/java/guru/bug/courses/srs/boundary/ServiceResourceTest.java
> +        System.out.println(resp);
I removed the printing and added some validations

2021-07-04 08:31 UTC, MaryR-code commented
> There is a failing test because of an earlier bug in changeLog-0002.xml
> There is a unique constraint on the default_duration_minutes column. This is a mistake. The column default_duration_minutes cannot be unique.

I deleted constraint unique="true"

2021-07-04 17:32 UTC, yekaterinasavelyeva approved these changes

2021-07-09 16:23 UTC, dima-fedotovs approved these changes
Ok. Lets merge it! :)

2021-07-09 16:33 UTC, merged