Feature/7 user resource service
JavaIIPlus01/service-reservation-system pull request #27
Opened 2021-06-27 19:32 UTC by yekaterinasavelyeva

2021-07-02 16:39 UTC, dima-fedotovs requested changes
Please fix the version of quarkus-test-security in pom.xml

2021-07-02 16:39 UTC, dima-fedotovs commented on pom.xml
> +            <version>2.0.0.Final</version>
Don't specify the version. (Moreover incorrect version). There is imported BOM here. All compatible versions are specified there. Only you need is to define dependency (without version)

2021-07-04 08:34 UTC, MaryR-code approved these changes

2021-07-09 16:18 UTC, dima-fedotovs approved these changes
Let's merge it

2021-07-09 16:34 UTC, merged