#2 add liquibase changesets to create tables services, service_provider, reservations
JavaIIPlus01/service-reservation-system pull request #9
Opened 2021-05-28 17:16 UTC by Evgshul

create changeset to create services tables

2021-05-28 17:34 UTC, dima-fedotovs requested changes
Everything is fine, except formatting. Please reformat the code. Try to keep lines not longer than 120-130 characters. Keep in mind readability. Empty lines sometimes do an incredibly good job. We are not only writing the code. From time to time, we need to read it too.

2021-05-28 17:34 UTC, dima-fedotovs commented on src/main/resources/db/changeLog-0002-service.xml
> +    <changeSet id="create table service_providers" author="Evgeny Shulgin">
Would propose to add empty lines between changesets. This will make it a little bit more readable.

2021-05-28 17:34 UTC, dima-fedotovs commented on src/main/resources/db/changeLog-0002-service.xml
> +               <constraints nullable="false" foreignKeyName="fk_reservations_service_provider_id" referencedTableName="service_providers" referencedColumnNames="id"/>
not everyone has a 48" monitor. It is recommended to split long lines to avoid necessity of horizontal scrolling from readers of this file.
The IDE could do this automatically with proper settings.

2021-05-28 17:42 UTC, Evgshul commented on src/main/resources/db/changeLog-0002-service.xml
> +    <changeSet id="create table service_providers" author="Evgeny Shulgin">
ok, I agreed. I'll re-format it

2021-05-28 18:07 UTC, Evgshul commented on src/main/resources/db/changeLog-0002-service.xml
> +               <constraints nullable="false" foreignKeyName="fk_reservations_service_provider_id" referencedTableName="service_providers" referencedColumnNames="id"/>
Thanks! I"ll re-format this 
I"ll stick to this rule in the future.

2021-05-28 18:30 UTC, Evgshul commented
done

2021-05-29 07:40 UTC, dima-fedotovs approved these changes
Everything is all right now. Could be merged.
One comment though: Not a big deal, but for the future: there are nullable and foreignKeyName on the same lines, but these are not related constraints. Better to make them on different lines. But again, this is just minor recommendation.

2021-05-29 07:58 UTC, merged